"""added_prj

Revision ID: 5217849a7050
Revises: 6e3d14bbe099
Create Date: 2023-05-30 18:03:33.766266

"""
from alembic import op
import sqlalchemy as sa
import litestar

# revision identifiers, used by Alembic.
revision = "5217849a7050"
down_revision = "6e3d14bbe099"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("_sentinel", sa.Integer(), nullable=True),
        sa.Column("id", litestar.contrib.sqlalchemy.types.GUID(length=16), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project")),
        sa.UniqueConstraint("slug", name=op.f("uq_project_slug")),
    )
    op.add_column("author", sa.Column("_sentinel", sa.Integer(), nullable=True))
    op.add_column("country", sa.Column("_sentinel", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("country", "_sentinel")
    op.drop_column("author", "_sentinel")
    op.drop_table("project")
    # ### end Alembic commands ###
