#!/bin/bash

# - runs Alembic migrations
# - starts Litestar application

set -o errexit
set -o pipefail
set -o nounset

echo Running migrations...
alembic upgrade head

echo Starting Litestar App...
uvicorn app.main:app
