#!/bin/bash

# - validates Gunicorn config
# - waits for Redis
# - waits for PostgreSQL
# - runs Alembic migrations
# - starts Starlite application
#
# Note: redis-ready and pg-ready scripts defined in `app.utils`.

set -o errexit
set -o pipefail
set -o nounset

# Check Gunicorn Config
gunicorn --check-config --config=gunicorn.conf.py app.main:app
echo "Gunicorn Config OK!"

# Wait for Redis
until redis-ready; do
  sleep 5
done

# Wait for PostgreSQL
until pg-ready; do
  sleep 5
done

echo Running migrations...
alembic upgrade head

echo Starting Starlite App...
gunicorn app.main:app
